name: Test app

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install SSL Certificates
      run: |
        dotnet dev-certs https --trust

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      env:
        CHATBRO_TELEGRAM_TOKEN: ${{ secrets.CHATBRO_TELEGRAM_TOKEN }}
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reqnroll-html-report
        path: '**/reports/reqnroll.html'
        if-no-files-found: warn
        retention-days: 7
